### ISSUE TITLE
Paper lantern gets removed when torch is placed on it (maybe acting as a plant?)

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#28]
![2020-02-04_07 31 01](https://user-images.githubusercontent.com/33978024/73748646-8a3f6900-4762-11ea-9d1f-56252b1b445b.png)

**Comment by dags-** [comment]
They were inheriting properties from grass (plants), presumably for the sound type.

I've fixed this now.

I believe these blocks would have had no-collision as a result of inheriting from plants - was that deliberate? My change makes them block movement, but this can be rectified if necessary.

**Comment by CreativeRealms** [comment]
They shouldn't walk through them.

**Comment by CreativeRealms** [comment]
Just tested build 58 and it didn't fix it. (also happens with thatch)
![2020-02-04_17 37 28](https://user-images.githubusercontent.com/33978024/73760614-4191ab00-4776-11ea-9fbe-99ffde044152.png)

**Comment by dags-** [comment]
It fixed the blocks you reported...

**Comment by CreativeRealms** [comment]
ConquestReforged-4.0.0-59-mc1.15.2 fixes the lanterns but not the thatch. Not sure if "will do for thatch" means that update was supposed to fix it or if you are doing it in a later one.

**Comment by dags-** [comment]
You can relate a build number to a specific commit by clicking the 'commit' link

**Comment by CreativeRealms** [comment]
I know. Anyways build 60 fixes it.
