### ISSUE TITLE
Grass Generation Issue

### ISSUE THREAD

**Issue by Avidjabber** [Conquest-Reforged/Indev#97]
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.1.jar

**Forge Version**    
1.15.2-forge-31.1.18

**Describe the bug**    
Vanilla World Generation has no grass in the world. Using bonemeal on the ground does spawn short grass correctly, but also spawns missing textures. Missing textures have no break sound and aren't able to be grabbed. When spawned directly from the creative menu, Tall Grass does appear correctly. Flowers are generated correctly otherwise, as are underwater plants. Only issue seems to be with the Grass. 

**Crash Log**    
This did not cause my game to crash.

**Screenshots/Video**    
![1](https://user-images.githubusercontent.com/61600445/75580742-e7f76600-5a2d-11ea-8f97-dd16d986b1ba.png)
![2](https://user-images.githubusercontent.com/61600445/75580748-e9c12980-5a2d-11ea-8955-27b8f0ee91b2.png)

**System Information (optional)**    
Total RAM:   16 GB
Allocated RAM:    8GB
CPU:    Intel I5-6300HQ 2.30GHz
GPU:  NVidia GeForce GTX 960M

**Comment by dags-** [comment]
CR replaces some vanilla block types in order to tweak their behaviour. In this case I think it's to allow grass to be placed on anything, not just grass/dirt etc.


Unfortunately, in some parts of vanilla's code (mostly worldgen, as it happens) references to the original blocks are hard-coded. I'm guessing `minecraft:grass` is one such block.


I've tested further and found:
- after removing the CR replacement, grass generates as expected
- after removing all custom code from CR's grass block and allowing it to replace vanilla's, the issue persists (confirming the problem is not an issue of logic inside our own code)

**Comment by dags-** [comment]
So to fix this, you'd need to loop through every biome feature and updated every reference to a grass blockstate with CR's version, which would be a bit cumbersome.

I'm not sure what problem was being resolved by registry replacing - could we not just offer CR's version of grass in the creative tab (ie registered as `conquest:grass`) and leave vanilla's alone?

**Comment by HIPPOKLEIDES** [comment]
Registry replacing accomplished the following:
1. grass model being transformed downwards so that it doesn't float when above a layer block
2. grass not being able to be placed anywhere (ie: a person could only place it above a grass block or dirt before)

Making a new CR grass block might be the better way to go, The vanilla grass will just cause a bit of inconsistency in some survival worlds with the other plants having the two aforementioned features.

**Comment by dags-** [comment]
Ah yeah, thanks. Well should we do the same for the other reg-replaced plants/flowers for consistency?

We're essentially going to have to do a find-and-replace on biome-feature `minecraft:grass` to get the CR version into world-gen. Could use the same system for all.

**Comment by HIPPOKLEIDES** [comment]
Sure, we can do that. Might cause some awkwardness with other mods, but I don't think many should depend on these plants for stuff like recipes (and if they do we can just make tags).

**Comment by dags-** [comment]
Oh right, affects recipes too. That rings a bell... we had this conversation on 1.12 didn't we XD

I'll see if I can get reg-replaced grass working in worldgen first, then fallback to the other thing if not.

**Comment by dags-** [comment]
A fix has been submitted for testing in dev build 138

**Comment by CreativeRealms** [comment]
Grass spawns but the missing texture issue with bonemeal still persists
![2020-03-05_23 04 01](https://user-images.githubusercontent.com/33978024/76025475-b272e100-5f35-11ea-8b90-35fe0fda29fc.png)

**Comment by HIPPOKLEIDES** [comment]
<del>Strangely, with the bonemeal, that's the case for all the small flowers (ie: poppy, oxeye_daisy) except for the dandelion. (getting rid of overrides for the flowers was getting rod of the air)</del>

edit: commented right after dags' comment. Yeah, might be better to just go with our own duplicates of the plants

**Comment by dags-** [comment]
Has anyone had chance to check build 141?

It should be applying the same fix to flowers now. I couldn't get the no-texture block to show when I tested, wondered if anyone else found anything?

**Comment by CreativeRealms** [comment]
Fixed on my end.

**Comment by SamMadeChannel** [comment]
I still get this in ConquestReforged-mc1.15.2-4.0.0-v0.2. 

Was your fix in this build yet?
